let x = {
    "draw": 0,
    "recordsTotal": 1,
    "recordsFiltered": 1,
    "data": [
        ["<span></span>", "<span class='text-center'>مناقصه</span>", "<span class='text-center'>زمان فروش اسناد</span>", "<span class='text-center'>1391/07/08  </span>", "<span class='text-center'>1390/07/08  </span>", "<span class='text-center'>1390/07/08  </span>", "<a href='/مناقصات-و-مزایدات/'>جزئیات</a>", "740"],
        ["<span></span>", "<span class='text-center'>مناقصه</span>", "<span class='text-center'>در حال فروش اسناد</span>", "<span class='text-center'>1391/07/11  </span>", "<span class='text-center'>1390/07/11  </span>", "<span class='text-center'>1390/07/11  </span>", "<a href='/مناقصات-و-مزایدات/'>جزئیات</a>", "740"],
        ["<span></span>", "<span class='text-center'></span>", "<span class='text-center'>در حال فروش اسناد</span>", "<span class='text-center'>1395/04/29  </span>", "<span class='text-center'>1395/05/05  </span>", "<span class='text-center'>1395/05/09  </span>", "<a href='/مناقصات-و-مزایدات/'>جزئیات</a>", "740"],
        ["<span></span>", "<span class='text-center'></span>", "<span class='text-center'>در حال فروش اسناد</span>", "<span class='text-center'>1395/07/12  </span>", "<span class='text-center'>1390/07/12  </span>", "<span class='text-center'>1390/07/12  </span>", "<a href='/مناقصات-و-مزایدات/'>جزئیات</a>", "740"],
        ["<span></span>", "<span class='text-center'></span>", "<span class='text-center'>در حال فروش اسناد</span>", "<span class='text-center'>1396/03/06  </span>", "<span class='text-center'>1390/03/06  </span>", "<span class='text-center'>1390/03/06  </span>", "<a href='/مناقصات-و-مزایدات/'>جزئیات</a>", "740"],
        ["<span></span>", "<span class='text-center'>مناقصه</span>", "<span class='text-center'>در حال فروش اسناد</span>", "<span class='text-center'>1399/03/02  </span>", "<span class='text-center'>1399/03/10  </span>", "<span class='text-center'>1399/03/16  </span>", "<a href='/مناقصات-و-مزایدات/'>جزئیات</a>", "740"],
        ["<span></span>", "<span class='text-center'>مزایده</span>", "<span class='text-center'>در حال فروش اسناد</span>", "<span class='text-center'>1399/03/31  </span>", "<span class='text-center'>1399/04/04  </span>", "<span class='text-center'>1399/04/13  </span>", "<a href='/مناقصات-و-مزایدات/'>جزئیات</a>", "740"],
        ["<span>  اجراي عمليات رفع حريم شبکه فشار متوسط دره گل مرحله دوم (نصب   کابل خودنگهدار)</span>", "<span class='text-center'></span>", "<span class='text-center'>در حال فروش اسناد</span>", "<span class='text-center'>1395/07/12  </span>", "<span class='text-center'>1395/07/17  </span>", "<span class='text-center'>1395/07/17  </span>", "<a href='/مناقصات-و-مزایدات/--اجراي-عمليات-رفع-حريم-شبکه-فشار-متوسط-دره-گل-مرحله-دوم-(نصب---کابل-خودنگهدار)'>جزئیات</a>", "740"],
        ["<span>  اجراي عمليات رفع حريم شبکه فشار متوسط دره گل مرحله دوم (نصب   کابل خودنگهدار)</span>", "<span class='text-center'></span>", "<span class='text-center'>در حال فروش اسناد</span>", "<span class='text-center'>1395/07/12  </span>", "<span class='text-center'>1397/07/17  </span>", "<span class='text-center'>1397/07/17  </span>", "<a href='/مناقصات-و-مزایدات/--اجراي-عمليات-رفع-حريم-شبکه-فشار-متوسط-دره-گل-مرحله-دوم-(نصب---کابل-خودنگهدار)'>جزئیات</a>", "740"],
        ["<span>  اصلاح تجهیزات شبکه منطقه مه خیز حد فاصل روستای کلبعلی تا گردنه سخوید.</span>", "<span class='text-center'></span>", "<span class='text-center'>در حال فروش اسناد</span>", "<span class='text-center'>1396/07/21  </span>", "<span class='text-center'>1396/08/23  </span>", "<span class='text-center'>1396/08/24  </span>", "<a href='/مناقصات-و-مزایدات/--اصلاح-تجهیزات-شبکه-منطقه-مه-خیز-حد-فاصل-روستای-کلبعلی-تا-گردنه-سخوید·'>جزئیات</a>", "740"],
        ["<span>  نظارت فني و كمي بر اجراي پروژه هاي توسعه و احداث و  اصلاح و بهینه سازی و  روشنايي معابر و  برق رساني روستايي و مانور فيدرها ،نصب انشعابات ديماندي وهمچنين بروزرساني وپياده سازي شبكه روي نرم افزار(ARC-GIS) فيمابين شركت توزيع نيروي برق استان يزد با پيمانك</span>", "<span class='text-center'>فراخوان ارزیابی کیفی</span>", "<span class='text-center'>در حال فروش اسناد</span>", "<span class='text-center'>1395/11/04  </span>", "<span class='text-center'>1395/11/15  </span>", "<span class='text-center'>1395/11/15  </span>", "<a href='/مناقصات-و-مزایدات/--نظارت-فني-و-كمي-بر-اجراي-پروژه-هاي-توسعه-و-احداث-و--اصلاح-و-بهینه-سازی-و--روشنايي-معابر-و--برق-رساني-روستايي-و-مانور-فيدرها-،نصب-انشعابات-ديماندي-وهمچنين-بروزرساني-وپياده-سازي-شبكه-روي-نرم-افزار(ARC–GIS)-فيمابين-شركت-توزيع-نيروي-برق-استان-يزد-با-پيمانك'>جزئیات</a>", "740"],
        ["<span> 	پياده سازي سيستم هوشمند سازي ويكپارچه مديريت انرژي ساختمان ستاد شركت توزيع برق استان يزد ، شامل طراحي ، تامين تجهيزات و نرم افزار مورد نياز ، نصب و راه اندازي ، آموزش </span>", "<span class='text-center'>مناقصه</span>", "<span class='text-center'>در حال فروش اسناد</span>", "<span class='text-center'>1391/12/04  </span>", "<span class='text-center'>1391/12/14  </span>", "<span class='text-center'>1391/12/21  </span>", "<a href='/مناقصات-و-مزایدات/-	پياده-سازي-سيستم-هوشمند-سازي-ويكپارچه-مديريت-انرژي-ساختمان-ستاد-شركت-توزيع-برق-استان-يزد-،-شامل-طراحي-،-تامين-تجهيزات-و-نرم-افزار-مورد-نياز-،-نصب-و-راه-اندازي-،-آموزش-'>جزئیات</a>", "740"], []]
}